blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
        #Example: /
        url(r'^$', PostLV.as_view(), name='index'),

        #Example: /post/
        url(r'^post/$', PostLV.as_view(), name='post_list'),

        #Example: /archive/
        #url(r'^archive/$', PostAV.as_view(), name='post_archive'),

        #Example: /post/django-example/
        url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

        #Example: /add/
        url(r'^add/$', PostCreateView.as_view(), name="add",),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.', null=True)
    content = models.TextField('CONTENT')
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

blog/views.py
from django.views.generic import ListView, DetailView
#from django.shortcuts import render
from blog.models import Post
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 10

class PostDV(DetailView):
    model = Post

class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'slug', 'content']
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
<h1>Blog List</h1>

{% for post in posts %}
<h2><li><a href = '{{ post.get_absolute_url }}'>{{ post.title }}</a></li></h2>
{% endfor %}

<br/>
<a href="{% url 'blog:add' %}">글쓰기</a>

blog/templates/blog/post_detail.html
<h2>{{ object.title }}</h2>
<div class="body">
	{{ object.content|linebreaks }}
</div>
<a href = "{% url 'blog:post_list' %}">목록</a>

blog/templates/blog/post_form.html
{% block title %}post_form.html{% endblock %}

{% block content %}
<div id="content">
	<form action="." method="post">{% csrf_token %}

	<fieldset class="aligned">

		<div class="form-row">
			{{ form.title.label_tag }} {{ form.title }}
		</div>

		<div class="form-row">
			{{ form.slug.label_tag }} {{ form.slug }}
		</div>

		<div class="form-row">
			{{ form.content.label_tag }} {{ form.content }}
		</div>
	</fieldset>

	<div class="submit-row">
		<input type="submit" value="Submit"/>
	</div>

	</form>
</div>
{% endblock %}